routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('contacts','ContactController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'phone_number', 'email', 'location',
    ];


    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Mail;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::latest()->paginate(5);
        return view('index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contact_form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'first_name'=>'required',
            'last_name'=>'required',
            'phone_number'=>'required|numeric|min:10',
            'email'=>'required|email|unique:users',
            'location'=>'required'
        ]);

        $contact = User::create($request->all());
        
        if(isset($contact)){
            // $sender = env('MAIL_USERNAME');
            $sender = 'tharanmca1@gmail.com';
            $to_name = $request->name;
            $to_email = $request->email;
            dd($sender);
            $data = array('name'=>$to_name, 'body' => 'Welcome mail');
            Mail::send('emails.mail', $data, function($message) use ($to_name, $to_email,$sender) {
            $message->to($to_email, $to_name)->subject('Welcome Mail');
            $message->from($sender,'Contact Form');
            });
        }

        return redirect('/contacts')->with('success', 'Contact updated!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact = User::find($id);
        return view('contact_form', compact('contact','view'));   
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = User::find($id);
        return view('contact_form', compact('contact'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // //
        // dd($request->all());
        $request->validate([
            'first_name'=>'required',
            'last_name'=>'required',
            'phone_number'=>'required|numeric|min:10',
            'email'=>'required|email|unique:users,email,'.$id,
            'location'=>'required'
        ]);

        $contact = User::find($id);
        $contact->update($request->all());
        $contact->save();

        return redirect('/contacts')->with('success', 'Contact updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = User::find($id);
        $contact->delete();

        return redirect('/contacts')->with('success', 'Contact deleted!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contact_form.blade.php
@extends('layouts.header')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2"><br>
    <h3 class="text-center">Add a contact</h3>
  <div>
  </br>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      @if(isset($contact))
        <form action="{{ route('contacts.update', $contact->id) }}"  method="post">
        @method('PATCH')
      @else
        <form method="post" action="{{ route('contacts.store') }}">
      @endif
          @csrf
          <div class="form-group">    
              <label for="first_name">First Name:</label>
              <input type="text" class="form-control" name="first_name" value="@if(old('first_name')){{ old('first_name') }} @else{{$contact->first_name??''}} @endif" required/>
          </div>

          <div class="form-group">
            <label for="last_name">Last Name:</label>
            <input type="text" class="form-control" name="last_name" value="@if(old('last_name')){{ old('last_name') }} @else {{$contact->last_name??''}} @endif" required/>
          </div>

          <div class="form-group">
            <label for="last_name">Phone Number:</label>
            <input type="text" class="form-control" name="phone_number" value="@if(old('phone_number')){{ old('phone_number') }} @else {{$contact->phone_number??''}} @endif" required/>
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email" value="@if(old('email')){{ old('email') }} @else {{$contact->email??''}} @endif" required/>
          </div>
          <div class="form-group">
              <label for="location">Location:</label>
              <input type="text" class="form-control" name="location" id="location" value="@if(old('location')){{ old('location') }} @else {{$contact->location??''}} @endif"/>
          </div>         
          @if(!isset($view))          
          <button type="submit" class="btn btn-success">Save Contact</button>
          @endif
          <a href="{{ route('contacts.index') }}" class="btn btn-primary"> << Back</a>
      </form>
  </div>
</div>
</div>
<script src="https://maps.google.com/maps/api/js?key=AIzaSyCGX6aGjOeMptlBNc0WF3vhm0SPMl1vNBE&libraries=places&callback=initAutocomplete" type="text/javascript"></script>
<script>
       google.maps.event.addDomListener(window, 'load', initialize);

       function initialize() {
           var input = document.getElementById('location');
           var autocomplete = new google.maps.places.Autocomplete(input);
           autocomplete.addListener();
       }
    </script>
@endsection

resources/views/index.blade.php
@extends('layouts.header')

@section('content')
<div class="row">
<div class="col-sm-12">
    <br>
    <div class="row">
        <div class="col-sm-6">
            <h3>Contacts Form</h3>
        </div>
        <div class="col-sm-6 text-right">
            <a href="{{ route('contacts.create') }}" class="btn btn-primary">Add Contact</a> 
        </div>
    </div>  
    </br> 
    <table class="table table-striped">
        <thead>
            <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Email</td>
            <td>Phone Number</td>
            <td>Location</td>
            <td colspan = 2>Actions</td>
            </tr>
        </thead>
        <tbody>
        @php $i=1; @endphp
            @foreach($data as $contact)
            <tr>
                <td>{{$i++}}</td>
                <td>{{$contact->first_name}} {{$contact->last_name}}</td>
                <td>{{$contact->email}}</td>
                <td>{{$contact->mobile_number}}</td>
                <td>{{$contact->location}}</td>
                <td>
                    <a href="{{ route('contacts.edit',$contact->id)}}" class="btn btn-primary">Edit</a>
                </td>
                <td>
                    <form action="{{ route('contacts.destroy', $contact->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
<div>
</div>
@endsection

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact Form</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    @yield('content')
  </div>  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>